version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "50051:50051"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
